sudo: false

language: c++
compiler:
 - clang
 - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
 - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" != "osx" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi

script: ./travis-build.sh

os:
 - linux
 - osx
 
osx_image: xcode9.3beta

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
 apt:
  sources:
   - llvm-toolchain-trusty-5.0
   - ubuntu-toolchain-r-test
  packages:
   - gcc-7
   - g++-7
   - libedit-dev
   - clang-5.0